export {default as Education} from './Education'
export {default as Projects} from './Projects'
export {default as Skills} from './Skills'
export {default as Navbar} from './Navbar'
export {default as Coding} from './Coding'
export {default as Contact} from './Contact'
export {default as Theme} from './Theme'